GET http://localhost:8080/api/foo
Accept: application/json


###
POST http://localhost:8080/api/bar
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZVZFdNOE1wY1BuZzl2VlNTdXN2aSJ9.eyJpc3MiOiJodHRwczovL2Rldi1lcm5lc3RvbWFyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJGdXZGTEk5WVl1b2s0WjZBcEVxSThzcEoweWpnNm0zckBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9zYWtpbGEudWNiLmVkdS5ibyIsImlhdCI6MTYzNzg4ODA2NywiZXhwIjoxNjM3OTc0NDY3LCJhenAiOiJGdXZGTEk5WVl1b2s0WjZBcEVxSThzcEoweWpnNm0zciIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.WpoxK9NB2R86QEXOG4oMQICzBojMutAtFr7FEu0Fd9fF8AOwVrHN2pGfEzXeIm4q_Z8qscEkcIPjwTDgQmXt3upGta5SaSk2z42KbDzsW3ecGC6gAeYBHVQ6srkBzKEuTBvao-8P9_OF7sYSRj0l7SPt523be30-yosEfWlDS2L8M70dRyfhcpGqDLUB4YpHFcPeZcKMXSfcMpgWj352Dqj8tP5K3OsNU403K3EYvYeAZnjzrTmCOVnaIpfpBVn2YpBbhBkDlJlVch_d3tWy420qZOk365s2PKRhIxJnduFSc7baXfrsIFAVefNRtKzi7PO9eOVj3TlbVz0yri7r4g

{
"Test": "test 1"
}
